language: python
python:
- 2.7
sudo: required
services:
- docker
addons:
  apt:
    packages:
    - unixodbc-dev
env:
  global:
  - EXAODBC=EXASOL_ODBC-6.0.2
  - EXAODBC_URL=https://www.exasol.com/support/secure/attachment/52896/
  - ODBCINI=$HOME/odbc.ini
  - ODBCSYSINI=$HOME
  - EXAHOST="127.0.0.1:8899"
  - EXAUSER="sys"
  - EXAPW="exasol"
  - ODBC_HOST="127.0.0.1:8899"
  - secure: dl4X1Hi/PbYKhDn6dVJvX6sB+EhgwMBtZ4quiRsEnaqegi83zzWlPRYGuH3+vicivI+KF9YGnPLuVj5ha3JDuznYS5CSizPUHUAFvV/xYgGE1PsBhaYcrSSZfpUk1yOkX09ZrRSH6dI6rT+jFBGmj0GoqgzdnrTnkG31s63k5aMwAEJYLs48dE/zeRfX2ttE8V80uJWK5fvlFiKO3PwKBWUWvjB+ZuvsfVWuh/4H5k1OG9BabcGZz+G7i32wDN5P9xp2VrlfyH5cO3q2zmJ0Em+q0ZDXbqCwNcx5rLsUPnVuZiuXfLNghmHUIrmC8n4Rg950PbDmYWODLb2P7S3QKdf8bMtmaf/u0UrEJjL3hP6LIV5eAlNsppfHIRc/CR9sftq0dlcFNXu6I6oNGWqR1rc7MmCeb3kmHedYACtmfnCWWOcPD8MXLJKafTlEkcYPzyjzLcvGaqsRVXlaQBj7NKQLxNrGGSKYoh1xdWwr3Cc19wNQeyCbeL/PSZNmcV7tEx/CraRC0QQJFIMU2B+JYWvPz2f+ndqfPSfzQAToRWJffbXgThI/z5NJj+XOB9mjEQaDByfDU9P2Pmp8uVHNJdEw3RalwvRrxMJLU7/awQdFjB93qYF/L0LprsLltUGtiwVSScLdZ0ZVGLE2kqqNRZZu1/qBgOPuMh1cAG2ex/4=
before_install:
- curl -L $TEST_PATH -o my_test.txt
- cat my_test.txt
- git clone --depth=50 --branch=master https://github.com/EXASOL/python-exasol.git
- cp -R python-exasol/* .
- ./tests/write-odbc-ini-in-home.sh "$TRAVIS_BUILD_DIR/EXASOL_ODBC-6.0.2"
- chmod +x test/testing_files/*
- "./test/testing_files/exasol_docker.sh"
- wget www.unixodbc.org/unixODBC-2.3.4.tar.gz
- wget $EXAODBC_URL$EXAODBC".tar.gz"
install:
- pip install pyodbc
- pip install pandas
- tar -xzf unixODBC-2.3.4.tar.gz
- "./unixODBC-2.3.4/configure --prefix=$HOME/unixodbc"
- make
- make install
- tar -xzf $EXAODBC".tar.gz"
- "./$EXAODBC/config_odbc --mode=config --host=$EXAHOST --user=$EXAUSER --password=$EXAPW"
- python setup.py install --prefix=$HOME/exa_py
script:
- "./test/testing_files/mock_test.sh"
- "./test/testing_files/test_exasol.sh"
- "./test/testing_files/test_mysql.sh"
- "./test/testing_files/test_sqlserver.sh"
- "./test/testing_files/test_postgres.sh"
