language: java

services:
  - mysql
  - postgresql

before_install:
  - mysql -u root --password="" < testing_files/mysql_datatypes_test.sql

before_script:
  - psql -U postgres -d postgres -a -f ./testing_files/postgres_datatypes_test.sql
  
addons:
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server
      - mysql-client
      
  postgresql: "9.4"