language: python

python:
    - 2.7

sudo: required

services:
  - docker
  
addons:
  apt:
    packages:
      - unixodbc-dev
      
env:
  global:
    - EXAODBC=EXASOL_ODBC-6.0.2
    - EXAODBC_URL=https://www.exasol.com/support/secure/attachment/52896/
    - ODBCINI=$HOME/odbc.ini
    - ODBCSYSINI=$HOME
    - EXAHOST="127.0.0.1:8899"
    - EXAUSER="sys"
    - EXAPW="exasol"
    - ODBC_HOST="127.0.0.1:8899"
    #https://www.exasol.com/support/secure/attachment/52896/EXASOL_ODBC-6.0.2.tar.gz

before_install:
    
    #cloning the python-exasol package repository
    - git clone --depth=50 --branch=master https://github.com/EXASOL/python-exasol.git
    - cp -R python-exasol/* .
    
    # move write odbc inis to home
    - ./tests/write-odbc-ini-in-home.sh "$TRAVIS_BUILD_DIR/EXASOL_ODBC-6.0.2"

    # allow test files to be executed
    - chmod +x testing_files/exasol_docker.sh
    - chmod +x testing_files/mock_test.sh
    - chmod +x testing_files/test_mysql.sh
    - chmod +x testing_files/test_sqlserver.sh
    - chmod +x testing_files/test_postgres.sh
    
    #install exasol image and run container
    - ./testing_files/exasol_docker.sh
    
    # get unixODBC
    - wget www.unixodbc.org/unixODBC-2.3.4.tar.gz
    
    # get EXAODBC    
    - wget $EXAODBC_URL$EXAODBC".tar.gz"

install:
    - pip install pyodbc
    - pip install pandas
    
    # install unixodbc
    - tar -xzf unixODBC-2.3.4.tar.gz
    - ./unixODBC-2.3.4/configure --prefix=$HOME/unixodbc
    - make
    - make install

    # install EXAODBC
    - tar -xzf $EXAODBC".tar.gz"
    - ./$EXAODBC/config_odbc --mode=config --host=$EXAHOST --user=$EXAUSER --password=$EXAPW
    
    # install py sdk
    - python setup.py install --prefix=$HOME/exa_py
    
script: 
    - ./testing_files/mock_test.sh
    - ./testing_files/test_mysql.sh
    - ./testing_files/test_sqlserver.sh
    - ./testing_files/test_postgres.sh