language: python
python:
- 2.7
sudo: required
services:
- docker
addons:
  apt:
    packages:
    - unixodbc-dev
env:
  global:
  - EXAODBC=EXASOL_ODBC-6.0.2
  - EXAODBC_URL=https://www.exasol.com/support/secure/attachment/52896/
  - ODBCINI=$HOME/odbc.ini
  - ODBCSYSINI=$HOME
  - EXAHOST="127.0.0.1:8899"
  - EXAUSER="sys"
  - EXAPW="exasol"
  - ODBC_HOST="127.0.0.1:8899"
  - PYTHONPATH=$HOME/exa_py/lib/python2.7/site-packages
  - secure: dl4X1Hi/PbYKhDn6dVJvX6sB+EhgwMBtZ4quiRsEnaqegi83zzWlPRYGuH3+vicivI+KF9YGnPLuVj5ha3JDuznYS5CSizPUHUAFvV/xYgGE1PsBhaYcrSSZfpUk1yOkX09ZrRSH6dI6rT+jFBGmj0GoqgzdnrTnkG31s63k5aMwAEJYLs48dE/zeRfX2ttE8V80uJWK5fvlFiKO3PwKBWUWvjB+ZuvsfVWuh/4H5k1OG9BabcGZz+G7i32wDN5P9xp2VrlfyH5cO3q2zmJ0Em+q0ZDXbqCwNcx5rLsUPnVuZiuXfLNghmHUIrmC8n4Rg950PbDmYWODLb2P7S3QKdf8bMtmaf/u0UrEJjL3hP6LIV5eAlNsppfHIRc/CR9sftq0dlcFNXu6I6oNGWqR1rc7MmCeb3kmHedYACtmfnCWWOcPD8MXLJKafTlEkcYPzyjzLcvGaqsRVXlaQBj7NKQLxNrGGSKYoh1xdWwr3Cc19wNQeyCbeL/PSZNmcV7tEx/CraRC0QQJFIMU2B+JYWvPz2f+ndqfPSfzQAToRWJffbXgThI/z5NJj+XOB9mjEQaDByfDU9P2Pmp8uVHNJdEw3RalwvRrxMJLU7/awQdFjB93qYF/L0LprsLltUGtiwVSScLdZ0ZVGLE2kqqNRZZu1/qBgOPuMh1cAG2ex/4=
  - secure: cWmEaE8jkhCowwugSJ8TSRHWEVERO3plvrT3AEgLrkFW/3j74hIILS/wgmijmzmnCWjndEBOTUs861UYtfIF1ke5mnP+SkXBo2wIReS9FDLnlfBF9W7hvrOGGNboF/dZ4UJ05ZYFOKlGpltzMCHMxzsb/aXXNVSqn978wb5PV7PNmLBcAuqGyRw6Tmt8mVV5yZqhEFEymfvxRiO7u3uJGzJ6iL8DrOdobTKqyg9lSKMCaKuJ6YB1dsgvBsw1bW/Dh70ZYDOnZYfXVag81dZ2pJQ2oJE8nTH6fYyJ33TuMpPzQwhq3lFKtxTtw5Pt3vEGF2O7rtYbRSzK8OH9/Y/JWpzyslnmMvsbnVaz1zL06uRcinCs3uXlJT6b56Gr28Y5ojtzPEMSrS4kEpEKphhZK0PDpjO9s/+pjrpvXl93fCw7QIl3rKikfoklvgz6mXyxC4I+dg1rgU0x4EAhz46+tmMIYsV7UNYn/nz5f6pQrj3PLgGUcA3L4eEMHNALN0PBt4AwRWq7VqGIxLIpRt2DKZUF90QVGPwXn6iPWlqR+7Xrhy5gzLZxz12nVbNaDsu6TxlIV3XbNojZTtxRIomSTPMNitE1xCdNOWy7lnfDLn+Bvyc1T1pTtZtTl2H6QZuQ3Qsxxmc02VVjx2JiplHP8eF0mxReiEvlb9ttpbWVTcg=
  - secure: GsjCCwxyA6AGTW66yuVpRr3qW0UFoyHbVD5PRNrevXlPtEWTZUNc/UtU0IU5klTBIkJmwjMrXmRwCLt4cJikKCtx27NTRZrV+/1QhZu5Ko4SRBfIToB8EXgMUBG1C4UWwMH6p/k4M436s9pO+/lge+vqVp27oxdK1EhBJLZSi3v++wX2ul/N1N8mDShAEGu3dsIfL3WnA/0ED1tLDbFNJFp0cgbUG0ZGxenT6L9FdkHno70tn/OjsR9MNfNDHAIScP8aOWfBAhi0CS7vmnhMkJNuN7IQcIrScHgLc3mszhh8aVB/bVNhshb+hJI0+85DoevY+ReUbXjxYc5Wj6Y8VEZtsZCDvzlbeAF5OwsM9wxSf3C7qxMCkIP5OXYiHja//w9xnewzfaZHC2c9vixrFivA1VeaB3MjkVX1tCd8wFtsfHWwMulMul4j9bZTxdan1iw1t+NZOXTHC35tf6PhdEbep3Z3/JapEvQZjYFRwAO6Nc+FB1zizZfiuBQ6QuRIV8yTzdc47a1ZtB2karaZwnMcmDqJKTU9ea0I66zJTi9jTvygwTu0vRZmD0WbFy4A3q1lxhZex4MJzSYSbWzgB65TlQrP5vvcm+4yRODpSD1nbA/y7TnJblGz04fgK9rCHJSEN5zg0JKKmnj7E5/lx6Gfx3rsWXEEsU9qGY3dCrs=
  - secure: "GvKBWYhmaKD9VUtQe9a9pRoVRuTUKqH1MMzuGsMe5IGnCmJppINTX6ZhX3C6OpB3rFP7gsNFTimGyWUx5WMlErtRHvqGfWmoOUaB7Zc2jULvzdcgNLx/9qXj3l0YVw0arbHljKlDMH2N9961QnQvZKqQMmBxP/mjq4H0H1kMr7I60W+/TwwPAn8R9lWVYF0blFlPtcLin6rYF1DGx0Zze7WDvkmjUVFXeJ/Lymyi84VhQ5J08/4AsIvmmxsVwQHIM0sRVM0KsosdDRrp4cVlQgeAXNsAgzhZNnll6vGX134nVNor6KC0yz7WhkyoNAMSAJT15UBB7yyJDOirlIT8kuVX3RjxbeNnxMwy5JRD+RA8QN9XtVidQ9X9Xi6cXUheyH5t+KwoLdULTlKHSlKRZSv3ArdBBAt9wFH+lAvOviNDdoasTwNvecb9IngVU3peY8ypQTr+m+oEmLIU5/M7yg3fZelzDj3/p1qthZDS9ydhrv++eOQh5m7zrr7IANHsx7APs8niNWBXw7GL75g7reYLM0NQG/HPiXJ4BbvigOB6W4My5av9d8Zu6I84PESuY2djasHgDPw4Q1c+leZ54FOQL7RgvMuD6GObZvwj2yg5bkuK29gv7tU6VwXzVlJ0hk2Iaij7NblTt8MD+f63TwTCz58OHU4PEBHFJ3beo9A="

before_install:
- curl -L $TEST_PATH -o my_test.txt
- cat my_test.txt
- git clone --depth=50 --branch=master https://github.com/EXASOL/python-exasol.git
- cp -R python-exasol/* .
- ./tests/write-odbc-ini-in-home.sh "$TRAVIS_BUILD_DIR/EXASOL_ODBC-6.0.2"
- chmod +x test/testing_files/*
- "./test/testing_files/exasol_docker.sh"
- "source ./test/testing_files/export_exaplus_path.sh"
- echo $EXAPLUS_PATH
- wget www.unixodbc.org/unixODBC-2.3.4.tar.gz
- wget $EXAODBC_URL$EXAODBC".tar.gz"
install:
- pip install pyodbc
- pip install pandas
- tar -xzf unixODBC-2.3.4.tar.gz
- "./unixODBC-2.3.4/configure --prefix=$HOME/unixodbc"
- make
- make install
- tar -xzf $EXAODBC".tar.gz"
- "./$EXAODBC/config_odbc --mode=config --host=$EXAHOST --user=$EXAUSER --password=$EXAPW"
- python setup.py install --prefix=$HOME/exa_py
script:
- "./test/testing_files/mock_test.sh"
- "./test/testing_files/test_mysql.sh"
- "./test/testing_files/test_db2.sh"
- "./test/testing_files/test_oracle.sh"
- "./test/testing_files/test_exasol.sh"
- "./test/testing_files/test_sqlserver.sh"
- "./test/testing_files/test_postgres.sh"
