language: sql
services:
  - mysql
before_install:
  - mysql -u root --password="root" < testing_files/mysql_datatypes_test.sql
  
addons:
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server
      - mysql-client